### ISSUE TITLE
Whitelisting does not work

### ISSUE THREAD

**Issue by MichiFr** [sfeakes/ipfire-scripts#2]
Hi,
while trying to use this script for IPFire core 111 (unbound) I noticed that whitelisting a domain does actually not work. Blacklisting, however, obviously works perfectly well.

I tried to add an entry Twitter.com to a file whitelist.hosts and executed the script using parameter -w /root/bin/whitelist.hosts.

Could you pls. check this?

Thanks,
Michael

**Comment by MichiFr** [comment]
Solved! copying the script arguments from my Winword documentation into the shell somehow switched the - sign into an octal or Unicode character and the script did not recognize the -w option anymore.

**Comment by seraphyn** [comment]
@MichiFr , You should close this issue  ;-)
